export const ADMIN_RESUME_REQUEST = 'ADMIN_RESUME_REQUEST';
export const ADMIN_RESUME_SUCCESS = 'ADMIN_RESUME_SUCCESS';
export const ADMIN_RESUME_FAIL = 'ADMIN_RESUME_FAIL';

export const NEW_RESUME_REQUEST = 'NEW_RESUME_REQUEST';
export const NEW_RESUME_SUCCESS = 'NEW_RESUME_SUCCESS';
export const NEW_RESUME_RESET = 'NEW_RESUME_RESET';
export const NEW_RESUME_FAIL = 'NEW_RESUME_FAIL';

export const DELETE_RESUME_REQUEST = 'DELETE_RESUME_REQUEST';
export const DELETE_RESUME_SUCCESS = 'DELETE_RESUME_SUCCESS';
export const DELETE_RESUME_RESET = 'DELETE_RESUME_RESET';
export const DELETE_RESUME_FAIL = 'DELETE_RESUME_FAIL';

export const UPDATE_RESUME_REQUEST = 'UPDATE_RESUME_REQUEST';
export const UPDATE_RESUME_SUCCESS = 'UPDATE_RESUME_SUCCESS';
export const UPDATE_RESUME_RESET = 'UPDATE_RESUME_RESET';
export const UPDATE_RESUME_FAIL = 'UPDATE_RESUME_FAIL';

export const RESUME_DETAILS_REQUEST = 'RESUME_DETAILS_REQUEST';
export const RESUME_DETAILS_SUCCESS = 'RESUME_DETAILS_SUCCESS';
export const RESUME_DETAILS_FAIL = 'RESUME_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
